name: '[CI] Module rspec'
description: 'Test module with rspec'
inputs:
  name:
    description: 'Module Name'
    required: true
  github_token:
    description: 'Github token'
    required: true

run:
  build_app:
    name: Build test application
    uses: mainio/gha-decidim-module/.github/workflows/build_app.yml@main
    secrets: inherit
