name: '[CI] Module rspec'
description: 'Test module with rspec'
inputs:
  name:
    description: 'Module Name'
    required: true
  github_token:
    description: 'Github token'
    required: true

jobs:
  build_app:
    name: Build test application
    uses: mainio/gha-decidim-module/.github/workflows/build_app.yml@main
    secrets: inherit
  main:
    needs: build_app
    name: Tests
    uses: mainio/gha-decidim-module/.github/workflows/ci_rspec.yml@main
    secrets: inherit
