# Replace the {MODULE_NAME} below with the actual name of the module.
name: "[CI] AccountabilityLocations"
on:
  workflow_run:
    workflows: ["[CI] Locatables"]
    types:
      - completed

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  main:
    name: Tests
    uses: mainio/gha-decidim-module/.github/workflows/ci_rspec.yml@main
    secrets: inherit
